name: sign_up
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_pro: ^1.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.15.5+2
  cloud_firestore: ^0.13.4+2
  provider: ^4.0.4
  flutter_spinkit: "^4.1.2"


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/a.jpg
    - images/b.jpg
    - images/c.jpg
    - images/d.jpg
    - images/e.jpg
    - images/f.jpg
    - images/g.jpg
    - images/h.jpg
    - images/i.jpg
    - images/j.jpg
    - assets/volt.jpeg
    - images/bo.png
    - images/ca.jpg
    - images/gha.jpg
    - images/la.jpg
    - images/abdel.png
    - images/banda.png
    - images/btec.png
    - images/car.jpg
    - images/elmor.jpg
    - images/fth.jpg
    - images/hayper.jpg
    - images/mall.png
    - images/sa.png
    - images/ta.jpg
    - images/Conditioner.jpg
    - images/coockers.jpg
    - images/fridge.jpg
    - images/laptob.jpg
    - images/mobile.jpg
    - images/ventilator.jpg
    - images/washMachine.jpg
    - images/heater.jpg
    - fridges/f1.jpg
    - fridges/f2.jpg
    - fridges/f3.jpg
    - fridges/f4.jpg
    - fridges/f5.jpg
    - fridges/f6.jpg
    - fridges/f7.jpg
    - fridges/f8.jpg
    - fridges/f9.jpg
    - fridges/f10.jpg
    - heater/h1.jpg
    - heater/h2.jpg
    - heater/h3.jpg
    - heater/h4.jpg
    - heater/h5.jpg
    - heater/h6.jpg
    - heater/h7.jpg
    - heater/h8.jpg
    - heater/h9.jpg
    - heater/h10.jpg
    - laptop/l1.jpg
    - laptop/l2.jpg
    - laptop/l3.jpg
    - laptop/l4.jpg
    - laptop/l5.jpg
    - laptop/l6.jpg
    - laptop/l7.jpg
    - laptop/l8.jpg
    - laptop/l9.jpg
    - laptop/l10.jpg
    - mobil/m1.jpg
    - mobil/m2.jpg
    - mobil/m3.jpg
    - mobil/m4.jpg
    - mobil/m5.jpg
    - mobil/m6.jpg
    - mobil/m7.jpg
    - mobil/m8.jpg
    - mobil/m9.jpg
    - mobil/m10.jpg
    - washing/w1.jpg
    - washing/w2.jpg
    - washing/w3.jpg
    - washing/w4.jpg
    - washing/w5.jpg
    - washing/w6.jpg
    - washing/w7.jpg
    - washing/w8.jpg
    - washing/w9.jpg
    - washing/w10.jpg





  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-VariableFont_wght.ttf
    - family: BreeSerif
      fonts:
        - asset: fonts/BreeSerif-Regular.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
